package cgeo.geocaching.files;

import cgeo.geocaching.location.Geopoint;
import cgeo.geocaching.models.Route;
import cgeo.geocaching.models.RouteItem;
import cgeo.geocaching.models.RouteSegment;
import cgeo.geocaching.utils.MatcherWrapper;

import android.sax.Element;
import android.sax.RootElement;

import androidx.annotation.NonNull;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.regex.Pattern;

/*
shortened example of a travelbug's itinerary kml generated by geocaching.com

<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
<Document>
    <name>Object's name</name>
    <Folder>
        <Placemark>
            <name>GCG493</name>
            <Point>
                <coordinates>-60.3502,46.6543,100 </coordinates>
            </Point>
            <Style>
                <Icon>
                    <href>http://chart.apis.google.com/chart?chst=d_bubble_icon_text_small&amp;chld=location|bbT|1|FFFFFF|000000</href>
                </Icon>
            </Style>
            <description><![CDATA[]]></description>
            <visibility>1</visibility>
        </Placemark>
    </Folder>
</Document>
</kml>
 */

public class KmlAsTrackParser extends AbstractTrackOrRouteParser implements AbstractTrackOrRouteParser.RouteParse {
    private String tempName = "";

    static final Pattern COORDINATES_PATTERN = Pattern.compile("^\\s*(-?\\d*\\.?\\d+)\\s*,\\s*(-?\\d*\\.?\\d+)(?:\\s*,\\s*(-?\\d*\\.?\\d+))?\\s*$");

    protected KmlAsTrackParser(final String namespaceIn, final String versionIn) {
        super(namespaceIn, versionIn, false);
    }

    @Override
    protected void setNameAndLatLonParsers() {
        points.getChild(namespace, "name").setEndTextElementListener(result::setName);
        point.getChild(namespace, "coordinates").setEndTextElementListener(s -> {
            final MatcherWrapper matchCoords = new MatcherWrapper(COORDINATES_PATTERN, s);
            if (matchCoords.find()) {
                final double latitude = Double.parseDouble(matchCoords.group(2));
                final double longitude = Double.parseDouble(matchCoords.group(1));
                final float altitude = matchCoords.groupCount() > 2 ? Float.parseFloat(matchCoords.group(3)) : 0f;
                temp.add(new Geopoint(latitude, longitude));
                tempElevation.add(altitude);
            }
        });
    }

    @NonNull
    public Route parse(@NonNull final InputStream stream) throws IOException, ParserException {
        final RootElement root = new RootElement(namespace, "kml");
        points = root.getChild(namespace, "Document");
        final Element folder = points.getChild(namespace, "Folder");
        final Element placemark = folder.getChild(namespace, "Placemark");
        point = placemark.getChild(namespace, "Point");
        point.getChild(namespace, "name").setEndTextElementListener(body -> tempName = body);
        point.setEndElementListener(() -> {
            if (!temp.isEmpty()) {
                result.add(new RouteSegment(new RouteItem(tempName, temp.get(temp.size() - 1)), temp, tempElevation, true));
                temp = new ArrayList<>();
            }
        });
        return super.parse(stream, root);
    }

}
