blank_issues_enabled: true
contact_links:
  - name: 3. Contact our c:geo support team
    url: https://mailxto.com/ft2ql4
    about: If you have questions regarding the usage of c:geo you should contact our support team by mail instead. Click open to proceed.
