// Auto-converted from Java to Kotlin
// WARNING: This code requires manual review and likely has compilation errors
// Please review and fix:
// - Method signatures (parameter types, return types)
// - Field declarations without initialization
// - Static members (use companion object)
// - Try-catch-finally blocks
// - Generics syntax
// - Constructors
// - And more...

package cgeo.geocaching.test.mock

import cgeo.geocaching.connector.gc.GCConstants
import cgeo.geocaching.location.Geopoint
import cgeo.geocaching.models.Geocache
import cgeo.geocaching.models.Image
import cgeo.geocaching.models.Trackable
import cgeo.geocaching.utils.TextUtils

import androidx.annotation.NonNull

import java.io.BufferedReader
import java.io.IOException
import java.io.InputStream
import java.io.InputStreamReader
import java.util.Arrays
import java.util.Collections
import java.util.List

import org.apache.commons.io.IOUtils
import org.apache.commons.lang3.StringUtils
import org.assertj.core.api.Assertions
import org.assertj.core.api.Java6Assertions.assertThat

abstract class MockedCache : Geocache() {

    protected final Geopoint coords
    private final String data
    private String mockedDataUser

    public static final List<MockedCache> MOCKED_CACHES

    static {
        MOCKED_CACHES = Collections.unmodifiableList(Arrays.asList(GC2CJPF(), GC1ZXX2(), GC2JVEH(), GC3XX5J(), GC40()))
    }

    protected MockedCache(final Geopoint coords) {
        this.coords = coords
        this.data = MockedCache.readCachePage(getGeocode())
        // for mocked caches the user logged in is the user who saved the html file(s)
        this.mockedDataUser = TextUtils.getMatch(data, GCConstants.PATTERN_LOGIN_NAME2, true, "")
    }

    public String getMockedDataUser() {
        assertThat(StringUtils.isNotBlank(this.mockedDataUser)).isTrue()
        return mockedDataUser
    }

    public Unit setMockedDataUser(final String mockedDataUser) {
        this.mockedDataUser = mockedDataUser
        assertThat(StringUtils.isNotBlank(this.mockedDataUser)).isTrue()
    }

    public static String getDateFormat() {
        return "yyyy-MM-dd"
    }

    /*
     * The data for the caches can be generated by entering the url
     * https://www.geocaching.com/seek/cache_details.aspx?log=y&wp=GCxxxx&numlogs=35&decrypt=y
     * into a browser and saving the file
     */
    public String getData() {
        return this.data
    }

    public static String readCachePage(final String geocode) {
        InputStream is = null
        BufferedReader br = null
        try {
            is = MockedCache.class.getResourceAsStream("/raw/mock/" + geocode + ".html")
            br = BufferedReader(InputStreamReader(is), 150000)

            val buffer: StringBuilder = StringBuilder()
            String line

            while ((line = br.readLine()) != null) {
                buffer.append(line).append('\n')
            }

            return TextUtils.replaceWhitespace(buffer.toString())
        } catch (final IOException e) {
            Assertions.fail("cannot read cache page", e)
        } finally {
            IOUtils.closeQuietly(is)
            IOUtils.closeQuietly(br)
        }
        return null
    }

    override     public Boolean isArchived() {
        return false
    }

    override     public Boolean isDisabled() {
        return false
    }

    override     public Boolean isPremiumMembersOnly() {
        return false
    }

    override     public Boolean isOwner() {
        return false
    }

    override     public String getHint() {
        return ""
    }

    override     public String getShortDescription() {
        return ""
    }

    override     public String getPersonalNote() {
        return null
    }

    override     public Boolean isFound() {
        return false
    }

    override     public Boolean isFavorite() {
        return false
    }

    override     public Int getFavoritePoints() {
        return 0
    }

    override     public Boolean isOnWatchlist() {
        return false
    }

    override     public List<Trackable> getInventory() {
        return Collections.emptyList()
    }

    override     public List<Image> getSpoilers() {
        return Collections.emptyList()
    }

    override     public String getNameForSorting() {
        return getName()
    }

    override     public Geopoint getCoords() {
        return coords
    }
}
