name: Build AVD cache

on:
  push:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch: 
    inputs:
      JDK_VERSION:
        description: The JDK version to use
        type: number
        default: 17
      API_LEVEL:
        description: The API Level version to use
        type: number
        default: 26

env:
  JDK_VERSION: ${{ inputs.JDK_VERSION || '17' }}
  API_LEVEL: ${{ inputs.API_LEVEL || '26' }}

jobs:
  avd-cache-update:
    # Using MacOs as it's better for running the emulator
    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-github-hosted-linux-vms
    runs-on: macos-latest
    steps:
      - name: Set up JDK ${{ env.JDK_VERSION }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.API_LEVEL }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.API_LEVEL }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
