name: Issue comment parser

on:
  issue_comment:
    types: [created]

permissions:
  actions: write
  issues: write
  pull-requests: write

jobs:
  rerun_pr_tests:
    name: rerun_pr_tests
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: kumy/rerun-actions@verbose
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        comment_id: ${{ github.event.comment.id }}
