name: Unlock Unit Tests 


on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unlock:
    runs-on: ubuntu-latest

    steps:
      - name: Unlock live tests
        if: always()
        run: |
          curl -X POST -qSs "https://mutex.kumy.org/api/client/${{ secrets.MUTEX_SECRET }}/mutex/unit-test?unlock"
