name: Unlock Unit Tests 


on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unlock:
    runs-on: ubuntu-latest

    steps:
      - name: Release a lock
        uses: suzuki-shunsuke/lock-action@latest
        with:
          mode: unlock
          key: unit-test
