#! /bin/sh
#

cd $(dirname $0)/../../main/src/androidTest/res/raw
for i in tb?????.htm* trackable_tb*.htm*; do
  tbcode=$(echo $i | sed -e 's/^.*\(tb[a-z0-9]*\)\..*$/\1/')
  echo downloading $tbcode: [fn: $i]
  echo --------------------
  curl "https://www.geocaching.com/track/details.aspx?tracker=$tbcode" > $i
  echo -------------------------------------------------------------------------------
done
